package aws_sdk.iotdata;

typedef JsonDocument = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob____________________________________________________________________________________________________________________________________________________________________________>;