package aws_sdk.iotdata;

typedef ListNamedShadowsForThingResponse = {
	/**
		The list of shadows for the specified thing.
	**/
	@:optional
	var results : NamedShadowList;
	/**
		The token for the next set of results, or null if there are no additional results.
	**/
	@:optional
	var nextToken : String;
	/**
		The Epoch date and time the response was generated by AWS IoT.
	**/
	@:optional
	var timestamp : Float;
};