package global.aws.cloudsearchdomain;

typedef _Blob = ts.AnyOf5<String, global.Buffer, node.stream.Readable, js.lib.Uint8Array, aws_sdk.Blob_____________________________________________________________________________________________________________________________________________________________________________________________________________________>;