package global.aws.redshift;

typedef CreateEventSubscriptionMessage = {
	/**
		The name of the event subscription to be created. Constraints:   Cannot be null, empty, or blank.   Must contain from 1 to 255 alphanumeric characters or hyphens.   First character must be a letter.   Cannot end with a hyphen or contain two consecutive hyphens.
	**/
	var SubscriptionName : String;
	/**
		The Amazon Resource Name (ARN) of the Amazon SNS topic used to transmit the event notifications. The ARN is created by Amazon SNS when you create a topic and subscribe to it.
	**/
	var SnsTopicArn : String;
	/**
		The type of source that will be generating the events. For example, if you want to be notified of events generated by a cluster, you would set this parameter to cluster. If this value is not specified, events are returned for all Amazon Redshift objects in your AWS account. You must specify a source type in order to specify source IDs. Valid values: cluster, cluster-parameter-group, cluster-security-group, cluster-snapshot, and scheduled-action.
	**/
	@:optional
	var SourceType : String;
	/**
		A list of one or more identifiers of Amazon Redshift source objects. All of the objects must be of the same type as was specified in the source type parameter. The event subscription will return only events generated by the specified objects. If not specified, then events are returned for all objects within the source type specified. Example: my-cluster-1, my-cluster-2 Example: my-snapshot-20131010
	**/
	@:optional
	var SourceIds : SourceIdsList;
	/**
		Specifies the Amazon Redshift event categories to be published by the event notification subscription. Values: configuration, management, monitoring, security
	**/
	@:optional
	var EventCategories : EventCategoriesList;
	/**
		Specifies the Amazon Redshift event severity to be published by the event notification subscription. Values: ERROR, INFO
	**/
	@:optional
	var Severity : String;
	/**
		A boolean value; set to true to activate the subscription, and set to false to create the subscription but not activate it.
	**/
	@:optional
	var Enabled : Bool;
	/**
		A list of tag instances.
	**/
	@:optional
	var Tags : TagList;
};