package global.aws.redshift;

typedef ModifyEventSubscriptionMessage = {
	/**
		The name of the modified Amazon Redshift event notification subscription.
	**/
	var SubscriptionName : String;
	/**
		The Amazon Resource Name (ARN) of the SNS topic to be used by the event notification subscription.
	**/
	@:optional
	var SnsTopicArn : String;
	/**
		The type of source that will be generating the events. For example, if you want to be notified of events generated by a cluster, you would set this parameter to cluster. If this value is not specified, events are returned for all Amazon Redshift objects in your AWS account. You must specify a source type in order to specify source IDs. Valid values: cluster, cluster-parameter-group, cluster-security-group, cluster-snapshot, and scheduled-action.
	**/
	@:optional
	var SourceType : String;
	/**
		A list of one or more identifiers of Amazon Redshift source objects. All of the objects must be of the same type as was specified in the source type parameter. The event subscription will return only events generated by the specified objects. If not specified, then events are returned for all objects within the source type specified. Example: my-cluster-1, my-cluster-2 Example: my-snapshot-20131010
	**/
	@:optional
	var SourceIds : SourceIdsList;
	/**
		Specifies the Amazon Redshift event categories to be published by the event notification subscription. Values: configuration, management, monitoring, security
	**/
	@:optional
	var EventCategories : EventCategoriesList;
	/**
		Specifies the Amazon Redshift event severity to be published by the event notification subscription. Values: ERROR, INFO
	**/
	@:optional
	var Severity : String;
	/**
		A Boolean value indicating if the subscription is enabled. true indicates the subscription is enabled
	**/
	@:optional
	var Enabled : Bool;
};