package global.aws.kinesis;

typedef Data = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob___________________________________________________________________________________________________________________________________________________________________________>;