package global.aws.amplify;

typedef StartDeploymentRequest = {
	/**
		The unique ID for an Amplify app.
	**/
	var appId : String;
	/**
		The name for the branch, for the job.
	**/
	var branchName : String;
	/**
		The job ID for this deployment, generated by the create deployment request.
	**/
	@:optional
	var jobId : String;
	/**
		The source URL for this deployment, used when calling start deployment without create deployment. The source URL can be any HTTP GET URL that is publicly accessible and downloads a single .zip file.
	**/
	@:optional
	var sourceUrl : String;
};