package global.aws.athena;

typedef GetQueryResultsOutput = {
	/**
		The number of rows inserted with a CREATE TABLE AS SELECT statement.
	**/
	@:optional
	var UpdateCount : Float;
	/**
		The results of the query execution.
	**/
	@:optional
	var ResultSet : ResultSet;
	/**
		A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call.
	**/
	@:optional
	var NextToken : String;
};