package global.aws.athena;

typedef ListWorkGroupsInput = {
	/**
		A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call.
	**/
	@:optional
	var NextToken : String;
	/**
		The maximum number of workgroups to return in this request.
	**/
	@:optional
	var MaxResults : Float;
};