package global.aws.athena;

typedef ListDataCatalogsOutput = {
	/**
		A summary list of data catalogs.
	**/
	@:optional
	var DataCatalogsSummary : DataCatalogSummaryList;
	/**
		A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call.
	**/
	@:optional
	var NextToken : String;
};