package global.aws.sns;

typedef Binary = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob_____________________________________________________________________________________________________________________________________________>;