package global.aws.lambda;

typedef _Blob = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob________________________________________________________________________________________________________________________________________________________________________>;