package global.aws.pinpoint;

typedef __Blob = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob_____________________________________________________________________________________________________________________________________________________________>;