package aws_sdk.cloudformation;

typedef DescribeTypeRegistrationInput = {
	/**
		The identifier for this registration request. This registration token is generated by CloudFormation when you initiate a registration request using  RegisterType .
	**/
	var RegistrationToken : String;
};