package global.aws.directconnect;

typedef LoaContent = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob_____________________________________________________________________________________________________________________________________________________________________________________________________>;