package global.aws.apigatewayv2;

typedef UpdateRouteRequest = {
	/**
		The API identifier.
	**/
	var ApiId : String;
	/**
		Specifies whether an API key is required for the route. Supported only for WebSocket APIs.
	**/
	@:optional
	var ApiKeyRequired : Bool;
	/**
		The authorization scopes supported by this route.
	**/
	@:optional
	var AuthorizationScopes : AuthorizationScopes;
	/**
		The authorization type for the route. For WebSocket APIs, valid values are NONE for open access, AWS_IAM for using AWS IAM permissions, and CUSTOM for using a Lambda authorizer For HTTP APIs, valid values are NONE for open access, or JWT for using JSON Web Tokens.
	**/
	@:optional
	var AuthorizationType : String;
	/**
		The identifier of the Authorizer resource to be associated with this route. The authorizer identifier is generated by API Gateway when you created the authorizer.
	**/
	@:optional
	var AuthorizerId : String;
	/**
		The model selection expression for the route. Supported only for WebSocket APIs.
	**/
	@:optional
	var ModelSelectionExpression : String;
	/**
		The operation name for the route.
	**/
	@:optional
	var OperationName : String;
	/**
		The request models for the route. Supported only for WebSocket APIs.
	**/
	@:optional
	var RequestModels : RouteModels;
	/**
		The request parameters for the route. Supported only for WebSocket APIs.
	**/
	@:optional
	var RequestParameters : RouteParameters;
	/**
		The route ID.
	**/
	var RouteId : String;
	/**
		The route key for the route.
	**/
	@:optional
	var RouteKey : String;
	/**
		The route response selection expression for the route. Supported only for WebSocket APIs.
	**/
	@:optional
	var RouteResponseSelectionExpression : String;
	/**
		The target for the route.
	**/
	@:optional
	var Target : String;
};