package aws_sdk.codegurureviewer;

typedef RecommendationSummary = {
	/**
		Name of the file on which a recommendation is provided.
	**/
	@:optional
	var FilePath : String;
	/**
		The recommendation ID that can be used to track the provided recommendations. Later on it can be used to collect the feedback.
	**/
	@:optional
	var RecommendationId : String;
	/**
		Start line from where the recommendation is applicable in the source commit or source branch.
	**/
	@:optional
	var StartLine : Float;
	/**
		Last line where the recommendation is applicable in the source commit or source branch. For a single line comment the start line and end line values are the same.
	**/
	@:optional
	var EndLine : Float;
	/**
		A description of the recommendation generated by CodeGuru Reviewer for the lines of code between the start line and the end line.
	**/
	@:optional
	var Description : String;
};