package aws_sdk.s3;

typedef Body = ts.AnyOf5<String, global.Buffer, node.stream.Readable, js.lib.Uint8Array, aws_sdk.Blob_____________________________________________________________________________________________________________________________________________________>;