package aws_sdk.s3;

typedef SSECustomerKey = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob_____________________________________________________________________________________________________________________________________________________>;