package aws_sdk.codepipeline;

typedef PutThirdPartyJobSuccessResultInput = {
	/**
		The ID of the job that successfully completed. This is the same ID returned from PollForThirdPartyJobs.
	**/
	var jobId : String;
	/**
		The clientToken portion of the clientId and clientToken pair used to verify that the calling entity is allowed access to the job and its details.
	**/
	var clientToken : String;
	/**
		Represents information about a current revision.
	**/
	@:optional
	var currentRevision : CurrentRevision;
	/**
		A token generated by a job worker, such as an AWS CodeDeploy deployment ID, that a successful job provides to identify a partner action in progress. Future jobs use this token to identify the running instance of the action. It can be reused to return more information about the progress of the partner action. When the action is complete, no continuation token should be supplied.
	**/
	@:optional
	var continuationToken : String;
	/**
		The details of the actions taken and results produced on an artifact as it passes through stages in the pipeline.
	**/
	@:optional
	var executionDetails : ExecutionDetails;
};