package aws_sdk.robomaker;

typedef CreateSimulationJobRequest = {
	/**
		Unique, case-sensitive identifier that you provide to ensure the idempotency of the request.
	**/
	@:optional
	var clientRequestToken : String;
	/**
		Location for output files generated by the simulation job.
	**/
	@:optional
	var outputLocation : OutputLocation;
	/**
		The logging configuration.
	**/
	@:optional
	var loggingConfig : LoggingConfig;
	/**
		The maximum simulation job duration in seconds (up to 14 days or 1,209,600 seconds. When maxJobDurationInSeconds is reached, the simulation job will status will transition to Completed.
	**/
	var maxJobDurationInSeconds : Float;
	/**
		The IAM role name that allows the simulation instance to call the AWS APIs that are specified in its associated policies on your behalf. This is how credentials are passed in to your simulation job.
	**/
	var iamRole : String;
	/**
		The failure behavior the simulation job.  Continue  Restart the simulation job in the same host instance.  Fail  Stop the simulation job and terminate the instance.
	**/
	@:optional
	var failureBehavior : String;
	/**
		The robot application to use in the simulation job.
	**/
	@:optional
	var robotApplications : RobotApplicationConfigs;
	/**
		The simulation application to use in the simulation job.
	**/
	@:optional
	var simulationApplications : SimulationApplicationConfigs;
	/**
		Specify data sources to mount read-only files from S3 into your simulation. These files are available under /opt/robomaker/datasources/data_source_name.   There is a limit of 100 files and a combined size of 25GB for all DataSourceConfig objects.
	**/
	@:optional
	var dataSources : DataSourceConfigs;
	/**
		A map that contains tag keys and tag values that are attached to the simulation job.
	**/
	@:optional
	var tags : TagMap;
	/**
		If your simulation job accesses resources in a VPC, you provide this parameter identifying the list of security group IDs and subnet IDs. These must belong to the same VPC. You must provide at least one security group and one subnet ID.
	**/
	@:optional
	var vpcConfig : VPCConfig;
	/**
		Compute information for the simulation job.
	**/
	@:optional
	var compute : Compute;
};