package aws_sdk.robomaker;

typedef DescribeSimulationJobResponse = {
	/**
		The Amazon Resource Name (ARN) of the simulation job.
	**/
	@:optional
	var arn : String;
	/**
		The name of the simulation job.
	**/
	@:optional
	var name : String;
	/**
		The status of the simulation job.
	**/
	@:optional
	var status : String;
	/**
		The time, in milliseconds since the epoch, when the simulation job was last started.
	**/
	@:optional
	var lastStartedAt : js.lib.Date;
	/**
		The time, in milliseconds since the epoch, when the simulation job was last updated.
	**/
	@:optional
	var lastUpdatedAt : js.lib.Date;
	/**
		The failure behavior for the simulation job.
	**/
	@:optional
	var failureBehavior : String;
	/**
		The failure code of the simulation job if it failed:  InternalServiceError  Internal service error.  RobotApplicationCrash  Robot application exited abnormally.  SimulationApplicationCrash   Simulation application exited abnormally.  BadPermissionsRobotApplication  Robot application bundle could not be downloaded.  BadPermissionsSimulationApplication  Simulation application bundle could not be downloaded.  BadPermissionsS3Output  Unable to publish outputs to customer-provided S3 bucket.  BadPermissionsCloudwatchLogs  Unable to publish logs to customer-provided CloudWatch Logs resource.  SubnetIpLimitExceeded  Subnet IP limit exceeded.  ENILimitExceeded  ENI limit exceeded.  BadPermissionsUserCredentials  Unable to use the Role provided.  InvalidBundleRobotApplication  Robot bundle cannot be extracted (invalid format, bundling error, or other issue).  InvalidBundleSimulationApplication  Simulation bundle cannot be extracted (invalid format, bundling error, or other issue).  RobotApplicationVersionMismatchedEtag  Etag for RobotApplication does not match value during version creation.  SimulationApplicationVersionMismatchedEtag  Etag for SimulationApplication does not match value during version creation.
	**/
	@:optional
	var failureCode : String;
	/**
		Details about why the simulation job failed. For more information about troubleshooting, see Troubleshooting.
	**/
	@:optional
	var failureReason : String;
	/**
		Unique, case-sensitive identifier that you provide to ensure the idempotency of the request.
	**/
	@:optional
	var clientRequestToken : String;
	/**
		Location for output files generated by the simulation job.
	**/
	@:optional
	var outputLocation : OutputLocation;
	/**
		The logging configuration.
	**/
	@:optional
	var loggingConfig : LoggingConfig;
	/**
		The maximum job duration in seconds. The value must be 8 days (691,200 seconds) or less.
	**/
	@:optional
	var maxJobDurationInSeconds : Float;
	/**
		The simulation job execution duration in milliseconds.
	**/
	@:optional
	var simulationTimeMillis : Float;
	/**
		The IAM role that allows the simulation instance to call the AWS APIs that are specified in its associated policies on your behalf.
	**/
	@:optional
	var iamRole : String;
	/**
		A list of robot applications.
	**/
	@:optional
	var robotApplications : RobotApplicationConfigs;
	/**
		A list of simulation applications.
	**/
	@:optional
	var simulationApplications : SimulationApplicationConfigs;
	/**
		The data sources for the simulation job.
	**/
	@:optional
	var dataSources : DataSources;
	/**
		The list of all tags added to the specified simulation job.
	**/
	@:optional
	var tags : TagMap;
	/**
		The VPC configuration.
	**/
	@:optional
	var vpcConfig : VPCConfigResponse;
	/**
		The network interface information for the simulation job.
	**/
	@:optional
	var networkInterface : NetworkInterface;
	/**
		Compute information for the simulation job.
	**/
	@:optional
	var compute : ComputeResponse;
};