package global.aws.swf;

typedef RespondDecisionTaskCompletedInput = {
	/**
		The taskToken from the DecisionTask.   taskToken is generated by the service and should be treated as an opaque value. If the task is passed to another process, its taskToken must also be passed. This enables it to provide its progress and respond with results.
	**/
	var taskToken : String;
	/**
		The list of decisions (possibly empty) made by the decider while processing this decision task. See the docs for the Decision structure for details.
	**/
	@:optional
	var decisions : DecisionList;
	/**
		User defined context to add to workflow execution.
	**/
	@:optional
	var executionContext : String;
};