package global.aws.inspector;

typedef CreateAssessmentTemplateRequest = {
	/**
		The ARN that specifies the assessment target for which you want to create the assessment template.
	**/
	var assessmentTargetArn : String;
	/**
		The user-defined name that identifies the assessment template that you want to create. You can create several assessment templates for an assessment target. The names of the assessment templates that correspond to a particular assessment target must be unique.
	**/
	var assessmentTemplateName : String;
	/**
		The duration of the assessment run in seconds.
	**/
	var durationInSeconds : Float;
	/**
		The ARNs that specify the rules packages that you want to attach to the assessment template.
	**/
	var rulesPackageArns : AssessmentTemplateRulesPackageArnList;
	/**
		The user-defined attributes that are assigned to every finding that is generated by the assessment run that uses this assessment template. An attribute is a key and value pair (an Attribute object). Within an assessment template, each key must be unique.
	**/
	@:optional
	var userAttributesForFindings : UserAttributeList;
};