package aws_sdk.lambda;

typedef BlobStream = ts.AnyOf5<String, global.Buffer, node.stream.Readable, js.lib.Uint8Array, aws_sdk.Blob________________________________________________________________________________________________________________________________________________________________________>;