package global.aws.stepfunctions;

typedef SendTaskSuccessInput = {
	/**
		The token that represents this task. Task tokens are generated by Step Functions when tasks are assigned to a worker, or in the context object when a workflow enters a task state. See GetActivityTaskOutput$taskToken.
	**/
	var taskToken : String;
	/**
		The JSON output of the task.
	**/
	var output : String;
};