package aws_sdk.wafregional;

typedef ByteMatchTargetString = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob___________________________________________________________________________________________________________________________________>;