package global.aws.iam;

typedef BootstrapDatum = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob________________________________________________________________________________________________________________________________________________________________________________>;