package aws_sdk.guardduty;

typedef GetThreatIntelSetResponse = {
	/**
		A user-friendly ThreatIntelSet name displayed in all findings that are generated by activity that involves IP addresses included in this ThreatIntelSet.
	**/
	var Name : String;
	/**
		The format of the threatIntelSet.
	**/
	var Format : String;
	/**
		The URI of the file that contains the ThreatIntelSet. For example: https://s3.us-west-2.amazonaws.com/my-bucket/my-object-key.
	**/
	var Location : String;
	/**
		The status of threatIntelSet file uploaded.
	**/
	var Status : String;
	/**
		The tags of the threat list resource.
	**/
	@:optional
	var Tags : TagMap;
};