package global.aws.ses;

typedef RawMessageData = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob__________________________________________________________________________________________________________________________________________________>;