package global.aws.guardduty;

typedef CreateThreatIntelSetRequest = {
	/**
		The unique ID of the detector of the GuardDuty account that you want to create a threatIntelSet for.
	**/
	var DetectorId : String;
	/**
		A user-friendly ThreatIntelSet name displayed in all findings that are generated by activity that involves IP addresses included in this ThreatIntelSet.
	**/
	var Name : String;
	/**
		The format of the file that contains the ThreatIntelSet.
	**/
	var Format : String;
	/**
		The URI of the file that contains the ThreatIntelSet. For example: https://s3.us-west-2.amazonaws.com/my-bucket/my-object-key.
	**/
	var Location : String;
	/**
		A Boolean value that indicates whether GuardDuty is to start using the uploaded ThreatIntelSet.
	**/
	var Activate : Bool;
	/**
		The idempotency token for the create request.
	**/
	@:optional
	var ClientToken : String;
	/**
		The tags to be added to a new threat list resource.
	**/
	@:optional
	var Tags : TagMap;
};