package global.aws.sqs;

typedef Binary = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob____________________________________________________________________________________________________________________________________________>;