package global.aws.polly;

typedef AudioStream = ts.AnyOf5<String, global.Buffer, node.stream.Readable, js.lib.Uint8Array, aws_sdk.Blob____________________________________________________________________________________________________________________________________________________________>;