package global.aws;

@:native("AWS.Support") extern class Support extends Service {
	/**
		Constructs a service object. This object has one method for each API operation.
	**/
	function new(?options:global.aws.support.ClientConfiguration);
	/**
		Adds one or more attachments to an attachment set.  An attachment set is a temporary container for attachments that you add to a case or case communication. The set is available for 1 hour after it's created. The expiryTime returned in the response is when the set expires.     You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Adds one or more attachments to an attachment set.  An attachment set is a temporary container for attachments that you add to a case or case communication. The set is available for 1 hour after it's created. The expiryTime returned in the response is when the set expires.     You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.AddAttachmentsToSetResponse) -> Void):Request<global.aws.support.AddAttachmentsToSetResponse, AWSError> { })
	function addAttachmentsToSet(params:global.aws.support.AddAttachmentsToSetRequest, ?callback:(err:AWSError, data:global.aws.support.AddAttachmentsToSetResponse) -> Void):Request<global.aws.support.AddAttachmentsToSetResponse, AWSError>;
	/**
		Adds additional customer communication to an AWS Support case. Use the caseId parameter to identify the case to which to add communication. You can list a set of email addresses to copy on the communication by using the ccEmailAddresses parameter. The communicationBody value contains the text of the communication.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Adds additional customer communication to an AWS Support case. Use the caseId parameter to identify the case to which to add communication. You can list a set of email addresses to copy on the communication by using the ccEmailAddresses parameter. The communicationBody value contains the text of the communication.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.AddCommunicationToCaseResponse) -> Void):Request<global.aws.support.AddCommunicationToCaseResponse, AWSError> { })
	function addCommunicationToCase(params:global.aws.support.AddCommunicationToCaseRequest, ?callback:(err:AWSError, data:global.aws.support.AddCommunicationToCaseResponse) -> Void):Request<global.aws.support.AddCommunicationToCaseResponse, AWSError>;
	/**
		Creates a case in the AWS Support Center. This operation is similar to how you create a case in the AWS Support Center Create Case page. The AWS Support API doesn't support requesting service limit increases. You can submit a service limit increase in the following ways:    Submit a request from the AWS Support Center Create Case page.   Use the Service Quotas RequestServiceQuotaIncrease operation.   A successful CreateCase request returns an AWS Support case number. You can use the DescribeCases operation and specify the case number to get existing AWS Support cases. After you create a case, use the AddCommunicationToCase operation to add additional communication or attachments to an existing case. The caseId is separate from the displayId that appears in the AWS Support Center. Use the DescribeCases operation to get the displayId.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Creates a case in the AWS Support Center. This operation is similar to how you create a case in the AWS Support Center Create Case page. The AWS Support API doesn't support requesting service limit increases. You can submit a service limit increase in the following ways:    Submit a request from the AWS Support Center Create Case page.   Use the Service Quotas RequestServiceQuotaIncrease operation.   A successful CreateCase request returns an AWS Support case number. You can use the DescribeCases operation and specify the case number to get existing AWS Support cases. After you create a case, use the AddCommunicationToCase operation to add additional communication or attachments to an existing case. The caseId is separate from the displayId that appears in the AWS Support Center. Use the DescribeCases operation to get the displayId.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.CreateCaseResponse) -> Void):Request<global.aws.support.CreateCaseResponse, AWSError> { })
	function createCase(params:global.aws.support.CreateCaseRequest, ?callback:(err:AWSError, data:global.aws.support.CreateCaseResponse) -> Void):Request<global.aws.support.CreateCaseResponse, AWSError>;
	/**
		Returns the attachment that has the specified ID. Attachments can include screenshots, error logs, or other files that describe your issue. Attachment IDs are generated by the case management system when you add an attachment to a case or case communication. Attachment IDs are returned in the AttachmentDetails objects that are returned by the DescribeCommunications operation.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Returns the attachment that has the specified ID. Attachments can include screenshots, error logs, or other files that describe your issue. Attachment IDs are generated by the case management system when you add an attachment to a case or case communication. Attachment IDs are returned in the AttachmentDetails objects that are returned by the DescribeCommunications operation.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.DescribeAttachmentResponse) -> Void):Request<global.aws.support.DescribeAttachmentResponse, AWSError> { })
	function describeAttachment(params:global.aws.support.DescribeAttachmentRequest, ?callback:(err:AWSError, data:global.aws.support.DescribeAttachmentResponse) -> Void):Request<global.aws.support.DescribeAttachmentResponse, AWSError>;
	/**
		Returns a list of cases that you specify by passing one or more case IDs. You can use the afterTime and beforeTime parameters to filter the cases by date. You can set values for the includeResolvedCases and includeCommunications parameters to specify how much information to return. The response returns the following in JSON format:   One or more CaseDetails data types.   One or more nextToken values, which specify where to paginate the returned records represented by the CaseDetails objects.   Case data is available for 12 months after creation. If a case was created more than 12 months ago, a request might return an error.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Returns a list of cases that you specify by passing one or more case IDs. You can use the afterTime and beforeTime parameters to filter the cases by date. You can set values for the includeResolvedCases and includeCommunications parameters to specify how much information to return. The response returns the following in JSON format:   One or more CaseDetails data types.   One or more nextToken values, which specify where to paginate the returned records represented by the CaseDetails objects.   Case data is available for 12 months after creation. If a case was created more than 12 months ago, a request might return an error.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.DescribeCasesResponse) -> Void):Request<global.aws.support.DescribeCasesResponse, AWSError> { })
	function describeCases(params:global.aws.support.DescribeCasesRequest, ?callback:(err:AWSError, data:global.aws.support.DescribeCasesResponse) -> Void):Request<global.aws.support.DescribeCasesResponse, AWSError>;
	/**
		Returns communications and attachments for one or more support cases. Use the afterTime and beforeTime parameters to filter by date. You can use the caseId parameter to restrict the results to a specific case. Case data is available for 12 months after creation. If a case was created more than 12 months ago, a request for data might cause an error. You can use the maxResults and nextToken parameters to control the pagination of the results. Set maxResults to the number of cases that you want to display on each page, and use nextToken to specify the resumption of pagination.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Returns communications and attachments for one or more support cases. Use the afterTime and beforeTime parameters to filter by date. You can use the caseId parameter to restrict the results to a specific case. Case data is available for 12 months after creation. If a case was created more than 12 months ago, a request for data might cause an error. You can use the maxResults and nextToken parameters to control the pagination of the results. Set maxResults to the number of cases that you want to display on each page, and use nextToken to specify the resumption of pagination.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.DescribeCommunicationsResponse) -> Void):Request<global.aws.support.DescribeCommunicationsResponse, AWSError> { })
	function describeCommunications(params:global.aws.support.DescribeCommunicationsRequest, ?callback:(err:AWSError, data:global.aws.support.DescribeCommunicationsResponse) -> Void):Request<global.aws.support.DescribeCommunicationsResponse, AWSError>;
	/**
		Returns the current list of AWS services and a list of service categories for each service. You then use service names and categories in your CreateCase requests. Each AWS service has its own set of categories. The service codes and category codes correspond to the values that appear in the Service and Category lists on the AWS Support Center Create Case page. The values in those fields don't necessarily match the service codes and categories returned by the DescribeServices operation. Always use the service codes and categories that the DescribeServices operation returns, so that you have the most recent set of service and category codes.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Returns the current list of AWS services and a list of service categories for each service. You then use service names and categories in your CreateCase requests. Each AWS service has its own set of categories. The service codes and category codes correspond to the values that appear in the Service and Category lists on the AWS Support Center Create Case page. The values in those fields don't necessarily match the service codes and categories returned by the DescribeServices operation. Always use the service codes and categories that the DescribeServices operation returns, so that you have the most recent set of service and category codes.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.DescribeServicesResponse) -> Void):Request<global.aws.support.DescribeServicesResponse, AWSError> { })
	function describeServices(params:global.aws.support.DescribeServicesRequest, ?callback:(err:AWSError, data:global.aws.support.DescribeServicesResponse) -> Void):Request<global.aws.support.DescribeServicesResponse, AWSError>;
	/**
		Returns the list of severity levels that you can assign to an AWS Support case. The severity level for a case is also a field in the CaseDetails data type that you include for a CreateCase request.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Returns the list of severity levels that you can assign to an AWS Support case. The severity level for a case is also a field in the CaseDetails data type that you include for a CreateCase request.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.DescribeSeverityLevelsResponse) -> Void):Request<global.aws.support.DescribeSeverityLevelsResponse, AWSError> { })
	function describeSeverityLevels(params:global.aws.support.DescribeSeverityLevelsRequest, ?callback:(err:AWSError, data:global.aws.support.DescribeSeverityLevelsResponse) -> Void):Request<global.aws.support.DescribeSeverityLevelsResponse, AWSError>;
	/**
		Returns the refresh status of the AWS Trusted Advisor checks that have the specified check IDs. You can get the check IDs by calling the DescribeTrustedAdvisorChecks operation. Some checks are refreshed automatically, and you can't return their refresh statuses by using the DescribeTrustedAdvisorCheckRefreshStatuses operation. If you call this operation for these checks, you might see an InvalidParameterValue error.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Returns the refresh status of the AWS Trusted Advisor checks that have the specified check IDs. You can get the check IDs by calling the DescribeTrustedAdvisorChecks operation. Some checks are refreshed automatically, and you can't return their refresh statuses by using the DescribeTrustedAdvisorCheckRefreshStatuses operation. If you call this operation for these checks, you might see an InvalidParameterValue error.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.DescribeTrustedAdvisorCheckRefreshStatusesResponse) -> Void):Request<global.aws.support.DescribeTrustedAdvisorCheckRefreshStatusesResponse, AWSError> { })
	function describeTrustedAdvisorCheckRefreshStatuses(params:global.aws.support.DescribeTrustedAdvisorCheckRefreshStatusesRequest, ?callback:(err:AWSError, data:global.aws.support.DescribeTrustedAdvisorCheckRefreshStatusesResponse) -> Void):Request<global.aws.support.DescribeTrustedAdvisorCheckRefreshStatusesResponse, AWSError>;
	/**
		Returns the results of the AWS Trusted Advisor check that has the specified check ID. You can get the check IDs by calling the DescribeTrustedAdvisorChecks operation. The response contains a TrustedAdvisorCheckResult object, which contains these three objects:    TrustedAdvisorCategorySpecificSummary     TrustedAdvisorResourceDetail     TrustedAdvisorResourcesSummary    In addition, the response contains these fields:    status - The alert status of the check: "ok" (green), "warning" (yellow), "error" (red), or "not_available".    timestamp - The time of the last refresh of the check.    checkId - The unique identifier for the check.      You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Returns the results of the AWS Trusted Advisor check that has the specified check ID. You can get the check IDs by calling the DescribeTrustedAdvisorChecks operation. The response contains a TrustedAdvisorCheckResult object, which contains these three objects:    TrustedAdvisorCategorySpecificSummary     TrustedAdvisorResourceDetail     TrustedAdvisorResourcesSummary    In addition, the response contains these fields:    status - The alert status of the check: "ok" (green), "warning" (yellow), "error" (red), or "not_available".    timestamp - The time of the last refresh of the check.    checkId - The unique identifier for the check.      You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.DescribeTrustedAdvisorCheckResultResponse) -> Void):Request<global.aws.support.DescribeTrustedAdvisorCheckResultResponse, AWSError> { })
	function describeTrustedAdvisorCheckResult(params:global.aws.support.DescribeTrustedAdvisorCheckResultRequest, ?callback:(err:AWSError, data:global.aws.support.DescribeTrustedAdvisorCheckResultResponse) -> Void):Request<global.aws.support.DescribeTrustedAdvisorCheckResultResponse, AWSError>;
	/**
		Returns the results for the AWS Trusted Advisor check summaries for the check IDs that you specified. You can get the check IDs by calling the DescribeTrustedAdvisorChecks operation. The response contains an array of TrustedAdvisorCheckSummary objects.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Returns the results for the AWS Trusted Advisor check summaries for the check IDs that you specified. You can get the check IDs by calling the DescribeTrustedAdvisorChecks operation. The response contains an array of TrustedAdvisorCheckSummary objects.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.DescribeTrustedAdvisorCheckSummariesResponse) -> Void):Request<global.aws.support.DescribeTrustedAdvisorCheckSummariesResponse, AWSError> { })
	function describeTrustedAdvisorCheckSummaries(params:global.aws.support.DescribeTrustedAdvisorCheckSummariesRequest, ?callback:(err:AWSError, data:global.aws.support.DescribeTrustedAdvisorCheckSummariesResponse) -> Void):Request<global.aws.support.DescribeTrustedAdvisorCheckSummariesResponse, AWSError>;
	/**
		Returns information about all available AWS Trusted Advisor checks, including the name, ID, category, description, and metadata. You must specify a language code. The AWS Support API currently supports English ("en") and Japanese ("ja"). The response contains a TrustedAdvisorCheckDescription object for each check. You must set the AWS Region to us-east-1.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Returns information about all available AWS Trusted Advisor checks, including the name, ID, category, description, and metadata. You must specify a language code. The AWS Support API currently supports English ("en") and Japanese ("ja"). The response contains a TrustedAdvisorCheckDescription object for each check. You must set the AWS Region to us-east-1.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.DescribeTrustedAdvisorChecksResponse) -> Void):Request<global.aws.support.DescribeTrustedAdvisorChecksResponse, AWSError> { })
	function describeTrustedAdvisorChecks(params:global.aws.support.DescribeTrustedAdvisorChecksRequest, ?callback:(err:AWSError, data:global.aws.support.DescribeTrustedAdvisorChecksResponse) -> Void):Request<global.aws.support.DescribeTrustedAdvisorChecksResponse, AWSError>;
	/**
		Refreshes the AWS Trusted Advisor check that you specify using the check ID. You can get the check IDs by calling the DescribeTrustedAdvisorChecks operation.  Some checks are refreshed automatically. If you call the RefreshTrustedAdvisorCheck operation to refresh them, you might see the InvalidParameterValue error.  The response contains a TrustedAdvisorCheckRefreshStatus object.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Refreshes the AWS Trusted Advisor check that you specify using the check ID. You can get the check IDs by calling the DescribeTrustedAdvisorChecks operation.  Some checks are refreshed automatically. If you call the RefreshTrustedAdvisorCheck operation to refresh them, you might see the InvalidParameterValue error.  The response contains a TrustedAdvisorCheckRefreshStatus object.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.RefreshTrustedAdvisorCheckResponse) -> Void):Request<global.aws.support.RefreshTrustedAdvisorCheckResponse, AWSError> { })
	function refreshTrustedAdvisorCheck(params:global.aws.support.RefreshTrustedAdvisorCheckRequest, ?callback:(err:AWSError, data:global.aws.support.RefreshTrustedAdvisorCheckResponse) -> Void):Request<global.aws.support.RefreshTrustedAdvisorCheckResponse, AWSError>;
	/**
		Resolves a support case. This operation takes a caseId and returns the initial and final state of the case.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
		
		Resolves a support case. This operation takes a caseId and returns the initial and final state of the case.    You must have a Business or Enterprise support plan to use the AWS Support API.    If you call the AWS Support API from an account that does not have a Business or Enterprise support plan, the SubscriptionRequiredException error message appears. For information about changing your support plan, see AWS Support.
	**/
	@:overload(function(?callback:(err:AWSError, data:global.aws.support.ResolveCaseResponse) -> Void):Request<global.aws.support.ResolveCaseResponse, AWSError> { })
	function resolveCase(params:global.aws.support.ResolveCaseRequest, ?callback:(err:AWSError, data:global.aws.support.ResolveCaseResponse) -> Void):Request<global.aws.support.ResolveCaseResponse, AWSError>;
	static var prototype : Support;
}