package aws_sdk.waf;

typedef ByteMatchTargetString = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob____________________________________________________________________________________________________________________________________>;