package global.aws.iot;

typedef ListViolationEventsRequest = {
	/**
		The start time for the alerts to be listed.
	**/
	var startTime : js.lib.Date;
	/**
		The end time for the alerts to be listed.
	**/
	var endTime : js.lib.Date;
	/**
		A filter to limit results to those alerts caused by the specified thing.
	**/
	@:optional
	var thingName : String;
	/**
		A filter to limit results to those alerts generated by the specified security profile.
	**/
	@:optional
	var securityProfileName : String;
	/**
		The token for the next set of results.
	**/
	@:optional
	var nextToken : String;
	/**
		The maximum number of results to return at one time.
	**/
	@:optional
	var maxResults : Float;
};