package global.aws.iot;

typedef Signature = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob_____________________________________________________________________________________________________________________________________________________________________________>;