package global.aws.codepipeline;

typedef ListWebhookItem = {
	/**
		The detail returned for each webhook, such as the webhook authentication type and filter rules.
	**/
	var definition : WebhookDefinition;
	/**
		A unique URL generated by CodePipeline. When a POST request is made to this URL, the defined pipeline is started as long as the body of the post request satisfies the defined authentication and filtering conditions. Deleting and re-creating a webhook makes the old URL invalid and generates a new one.
	**/
	var url : String;
	/**
		The text of the error message about the webhook.
	**/
	@:optional
	var errorMessage : String;
	/**
		The number code of the error.
	**/
	@:optional
	var errorCode : String;
	/**
		The date and time a webhook was last successfully triggered, in timestamp format.
	**/
	@:optional
	var lastTriggered : js.lib.Date;
	/**
		The Amazon Resource Name (ARN) of the webhook.
	**/
	@:optional
	var arn : String;
	/**
		Specifies the tags applied to the webhook.
	**/
	@:optional
	var tags : TagList;
};