package aws_sdk.rekognition;

typedef ImageBlob = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob_________________________________________________________________________________________________________________________________________________________>;