package aws_sdk.devicefarm;

typedef Artifact = {
	/**
		The artifact's ARN.
	**/
	@:optional
	var arn : String;
	/**
		The artifact's name.
	**/
	@:optional
	var name : String;
	/**
		The artifact's type. Allowed values include the following:   UNKNOWN   SCREENSHOT   DEVICE_LOG   MESSAGE_LOG   VIDEO_LOG   RESULT_LOG   SERVICE_LOG   WEBKIT_LOG   INSTRUMENTATION_OUTPUT   EXERCISER_MONKEY_OUTPUT: the artifact (log) generated by an Android fuzz test.   CALABASH_JSON_OUTPUT   CALABASH_PRETTY_OUTPUT   CALABASH_STANDARD_OUTPUT   CALABASH_JAVA_XML_OUTPUT   AUTOMATION_OUTPUT   APPIUM_SERVER_OUTPUT   APPIUM_JAVA_OUTPUT   APPIUM_JAVA_XML_OUTPUT   APPIUM_PYTHON_OUTPUT   APPIUM_PYTHON_XML_OUTPUT   EXPLORER_EVENT_LOG   EXPLORER_SUMMARY_LOG   APPLICATION_CRASH_REPORT   XCTEST_LOG   VIDEO   CUSTOMER_ARTIFACT   CUSTOMER_ARTIFACT_LOG   TESTSPEC_OUTPUT
	**/
	@:optional
	var type : String;
	/**
		The artifact's file extension.
	**/
	@:optional
	var extension : String;
	/**
		The presigned Amazon S3 URL that can be used with a GET request to download the artifact's file.
	**/
	@:optional
	var url : String;
};