package global.aws.securityhub;

typedef AwsSecurityFindingFilters = {
	/**
		The ARN generated by Security Hub that uniquely identifies a third-party company (security findings provider) after this provider's product (solution that generates findings) is registered with Security Hub.
	**/
	@:optional
	var ProductArn : StringFilterList;
	/**
		The AWS account ID that a finding is generated in.
	**/
	@:optional
	var AwsAccountId : StringFilterList;
	/**
		The security findings provider-specific identifier for a finding.
	**/
	@:optional
	var Id : StringFilterList;
	/**
		The identifier for the solution-specific component (a discrete unit of logic) that generated a finding. In various security-findings providers' solutions, this generator can be called a rule, a check, a detector, a plugin, etc.
	**/
	@:optional
	var GeneratorId : StringFilterList;
	/**
		A finding type in the format of namespace/category/classifier that classifies a finding.
	**/
	@:optional
	var Type : StringFilterList;
	/**
		An ISO8601-formatted timestamp that indicates when the security-findings provider first observed the potential security issue that a finding captured.
	**/
	@:optional
	var FirstObservedAt : DateFilterList;
	/**
		An ISO8601-formatted timestamp that indicates when the security-findings provider most recently observed the potential security issue that a finding captured.
	**/
	@:optional
	var LastObservedAt : DateFilterList;
	/**
		An ISO8601-formatted timestamp that indicates when the security-findings provider captured the potential security issue that a finding captured.
	**/
	@:optional
	var CreatedAt : DateFilterList;
	/**
		An ISO8601-formatted timestamp that indicates when the security-findings provider last updated the finding record.
	**/
	@:optional
	var UpdatedAt : DateFilterList;
	/**
		The native severity as defined by the security-findings provider's solution that generated the finding.
	**/
	@:optional
	var SeverityProduct : NumberFilterList;
	/**
		The normalized severity of a finding.
	**/
	@:optional
	var SeverityNormalized : NumberFilterList;
	/**
		The label of a finding's severity.
	**/
	@:optional
	var SeverityLabel : StringFilterList;
	/**
		A finding's confidence. Confidence is defined as the likelihood that a finding accurately identifies the behavior or issue that it was intended to identify. Confidence is scored on a 0-100 basis using a ratio scale, where 0 means zero percent confidence and 100 means 100 percent confidence.
	**/
	@:optional
	var Confidence : NumberFilterList;
	/**
		The level of importance assigned to the resources associated with the finding. A score of 0 means that the underlying resources have no criticality, and a score of 100 is reserved for the most critical resources.
	**/
	@:optional
	var Criticality : NumberFilterList;
	/**
		A finding's title.
	**/
	@:optional
	var Title : StringFilterList;
	/**
		A finding's description.
	**/
	@:optional
	var Description : StringFilterList;
	/**
		The recommendation of what to do about the issue described in a finding.
	**/
	@:optional
	var RecommendationText : StringFilterList;
	/**
		A URL that links to a page about the current finding in the security-findings provider's solution.
	**/
	@:optional
	var SourceUrl : StringFilterList;
	/**
		A data type where security-findings providers can include additional solution-specific details that aren't part of the defined AwsSecurityFinding format.
	**/
	@:optional
	var ProductFields : MapFilterList;
	/**
		The name of the solution (product) that generates findings.
	**/
	@:optional
	var ProductName : StringFilterList;
	/**
		The name of the findings provider (company) that owns the solution (product) that generates findings.
	**/
	@:optional
	var CompanyName : StringFilterList;
	/**
		A list of name/value string pairs associated with the finding. These are custom, user-defined fields added to a finding.
	**/
	@:optional
	var UserDefinedFields : MapFilterList;
	/**
		The name of the malware that was observed.
	**/
	@:optional
	var MalwareName : StringFilterList;
	/**
		The type of the malware that was observed.
	**/
	@:optional
	var MalwareType : StringFilterList;
	/**
		The filesystem path of the malware that was observed.
	**/
	@:optional
	var MalwarePath : StringFilterList;
	/**
		The state of the malware that was observed.
	**/
	@:optional
	var MalwareState : StringFilterList;
	/**
		Indicates the direction of network traffic associated with a finding.
	**/
	@:optional
	var NetworkDirection : StringFilterList;
	/**
		The protocol of network-related information about a finding.
	**/
	@:optional
	var NetworkProtocol : StringFilterList;
	/**
		The source IPv4 address of network-related information about a finding.
	**/
	@:optional
	var NetworkSourceIpV4 : IpFilterList;
	/**
		The source IPv6 address of network-related information about a finding.
	**/
	@:optional
	var NetworkSourceIpV6 : IpFilterList;
	/**
		The source port of network-related information about a finding.
	**/
	@:optional
	var NetworkSourcePort : NumberFilterList;
	/**
		The source domain of network-related information about a finding.
	**/
	@:optional
	var NetworkSourceDomain : StringFilterList;
	/**
		The source media access control (MAC) address of network-related information about a finding.
	**/
	@:optional
	var NetworkSourceMac : StringFilterList;
	/**
		The destination IPv4 address of network-related information about a finding.
	**/
	@:optional
	var NetworkDestinationIpV4 : IpFilterList;
	/**
		The destination IPv6 address of network-related information about a finding.
	**/
	@:optional
	var NetworkDestinationIpV6 : IpFilterList;
	/**
		The destination port of network-related information about a finding.
	**/
	@:optional
	var NetworkDestinationPort : NumberFilterList;
	/**
		The destination domain of network-related information about a finding.
	**/
	@:optional
	var NetworkDestinationDomain : StringFilterList;
	/**
		The name of the process.
	**/
	@:optional
	var ProcessName : StringFilterList;
	/**
		The path to the process executable.
	**/
	@:optional
	var ProcessPath : StringFilterList;
	/**
		The process ID.
	**/
	@:optional
	var ProcessPid : NumberFilterList;
	/**
		The parent process ID.
	**/
	@:optional
	var ProcessParentPid : NumberFilterList;
	/**
		The date/time that the process was launched.
	**/
	@:optional
	var ProcessLaunchedAt : DateFilterList;
	/**
		The date/time that the process was terminated.
	**/
	@:optional
	var ProcessTerminatedAt : DateFilterList;
	/**
		The type of a threat intelligence indicator.
	**/
	@:optional
	var ThreatIntelIndicatorType : StringFilterList;
	/**
		The value of a threat intelligence indicator.
	**/
	@:optional
	var ThreatIntelIndicatorValue : StringFilterList;
	/**
		The category of a threat intelligence indicator.
	**/
	@:optional
	var ThreatIntelIndicatorCategory : StringFilterList;
	/**
		The date/time of the last observation of a threat intelligence indicator.
	**/
	@:optional
	var ThreatIntelIndicatorLastObservedAt : DateFilterList;
	/**
		The source of the threat intelligence.
	**/
	@:optional
	var ThreatIntelIndicatorSource : StringFilterList;
	/**
		The URL for more details from the source of the threat intelligence.
	**/
	@:optional
	var ThreatIntelIndicatorSourceUrl : StringFilterList;
	/**
		Specifies the type of the resource that details are provided for.
	**/
	@:optional
	var ResourceType : StringFilterList;
	/**
		The canonical identifier for the given resource type.
	**/
	@:optional
	var ResourceId : StringFilterList;
	/**
		The canonical AWS partition name that the Region is assigned to.
	**/
	@:optional
	var ResourcePartition : StringFilterList;
	/**
		The canonical AWS external Region name where this resource is located.
	**/
	@:optional
	var ResourceRegion : StringFilterList;
	/**
		A list of AWS tags associated with a resource at the time the finding was processed.
	**/
	@:optional
	var ResourceTags : MapFilterList;
	/**
		The instance type of the instance.
	**/
	@:optional
	var ResourceAwsEc2InstanceType : StringFilterList;
	/**
		The Amazon Machine Image (AMI) ID of the instance.
	**/
	@:optional
	var ResourceAwsEc2InstanceImageId : StringFilterList;
	/**
		The IPv4 addresses associated with the instance.
	**/
	@:optional
	var ResourceAwsEc2InstanceIpV4Addresses : IpFilterList;
	/**
		The IPv6 addresses associated with the instance.
	**/
	@:optional
	var ResourceAwsEc2InstanceIpV6Addresses : IpFilterList;
	/**
		The key name associated with the instance.
	**/
	@:optional
	var ResourceAwsEc2InstanceKeyName : StringFilterList;
	/**
		The IAM profile ARN of the instance.
	**/
	@:optional
	var ResourceAwsEc2InstanceIamInstanceProfileArn : StringFilterList;
	/**
		The identifier of the VPC that the instance was launched in.
	**/
	@:optional
	var ResourceAwsEc2InstanceVpcId : StringFilterList;
	/**
		The identifier of the subnet that the instance was launched in.
	**/
	@:optional
	var ResourceAwsEc2InstanceSubnetId : StringFilterList;
	/**
		The date and time the instance was launched.
	**/
	@:optional
	var ResourceAwsEc2InstanceLaunchedAt : DateFilterList;
	/**
		The canonical user ID of the owner of the S3 bucket.
	**/
	@:optional
	var ResourceAwsS3BucketOwnerId : StringFilterList;
	/**
		The display name of the owner of the S3 bucket.
	**/
	@:optional
	var ResourceAwsS3BucketOwnerName : StringFilterList;
	/**
		The user associated with the IAM access key related to a finding.
	**/
	@:optional
	var ResourceAwsIamAccessKeyUserName : StringFilterList;
	/**
		The status of the IAM access key related to a finding.
	**/
	@:optional
	var ResourceAwsIamAccessKeyStatus : StringFilterList;
	/**
		The creation date/time of the IAM access key related to a finding.
	**/
	@:optional
	var ResourceAwsIamAccessKeyCreatedAt : DateFilterList;
	/**
		The name of the container related to a finding.
	**/
	@:optional
	var ResourceContainerName : StringFilterList;
	/**
		The identifier of the image related to a finding.
	**/
	@:optional
	var ResourceContainerImageId : StringFilterList;
	/**
		The name of the image related to a finding.
	**/
	@:optional
	var ResourceContainerImageName : StringFilterList;
	/**
		The date/time that the container was started.
	**/
	@:optional
	var ResourceContainerLaunchedAt : DateFilterList;
	/**
		The details of a resource that doesn't have a specific subfield for the resource type defined.
	**/
	@:optional
	var ResourceDetailsOther : MapFilterList;
	/**
		Exclusive to findings that are generated as the result of a check run against a specific rule in a supported standard, such as CIS AWS Foundations. Contains security standard-related finding details.
	**/
	@:optional
	var ComplianceStatus : StringFilterList;
	/**
		The veracity of a finding.
	**/
	@:optional
	var VerificationState : StringFilterList;
	/**
		The workflow state of a finding.
	**/
	@:optional
	var WorkflowState : StringFilterList;
	/**
		The status of the investigation into a finding. Allowed values are the following.    NEW - The initial state of a finding, before it is reviewed.    NOTIFIED - Indicates that the resource owner has been notified about the security issue. Used when the initial reviewer is not the resource owner, and needs intervention from the resource owner.    SUPPRESSED - The finding will not be reviewed again and will not be acted upon.    RESOLVED - The finding was reviewed and remediated and is now considered resolved.
	**/
	@:optional
	var WorkflowStatus : StringFilterList;
	/**
		The updated record state for the finding.
	**/
	@:optional
	var RecordState : StringFilterList;
	/**
		The ARN of the solution that generated a related finding.
	**/
	@:optional
	var RelatedFindingsProductArn : StringFilterList;
	/**
		The solution-generated identifier for a related finding.
	**/
	@:optional
	var RelatedFindingsId : StringFilterList;
	/**
		The text of a note.
	**/
	@:optional
	var NoteText : StringFilterList;
	/**
		The timestamp of when the note was updated.
	**/
	@:optional
	var NoteUpdatedAt : DateFilterList;
	/**
		The principal that created a note.
	**/
	@:optional
	var NoteUpdatedBy : StringFilterList;
	/**
		A keyword for a finding.
	**/
	@:optional
	var Keyword : KeywordFilterList;
};