package global.aws.securityhub;

typedef AwsSecurityFinding = {
	/**
		The schema version that a finding is formatted for.
	**/
	var SchemaVersion : String;
	/**
		The security findings provider-specific identifier for a finding.
	**/
	var Id : String;
	/**
		The ARN generated by Security Hub that uniquely identifies a product that generates findings. This can be the ARN for a third-party product that is integrated with Security Hub, or the ARN for a custom integration.
	**/
	var ProductArn : String;
	/**
		The identifier for the solution-specific component (a discrete unit of logic) that generated a finding. In various security-findings providers' solutions, this generator can be called a rule, a check, a detector, a plugin, etc.
	**/
	var GeneratorId : String;
	/**
		The AWS account ID that a finding is generated in.
	**/
	var AwsAccountId : String;
	/**
		One or more finding types in the format of namespace/category/classifier that classify a finding. Valid namespace values are: Software and Configuration Checks | TTPs | Effects | Unusual Behaviors | Sensitive Data Identifications
	**/
	var Types : TypeList;
	/**
		An ISO8601-formatted timestamp that indicates when the security-findings provider first observed the potential security issue that a finding captured.
	**/
	@:optional
	var FirstObservedAt : String;
	/**
		An ISO8601-formatted timestamp that indicates when the security-findings provider most recently observed the potential security issue that a finding captured.
	**/
	@:optional
	var LastObservedAt : String;
	/**
		An ISO8601-formatted timestamp that indicates when the security-findings provider created the potential security issue that a finding captured.
	**/
	var CreatedAt : String;
	/**
		An ISO8601-formatted timestamp that indicates when the security-findings provider last updated the finding record.
	**/
	var UpdatedAt : String;
	/**
		A finding's severity.
	**/
	var Severity : Severity;
	/**
		A finding's confidence. Confidence is defined as the likelihood that a finding accurately identifies the behavior or issue that it was intended to identify. Confidence is scored on a 0-100 basis using a ratio scale, where 0 means zero percent confidence and 100 means 100 percent confidence.
	**/
	@:optional
	var Confidence : Float;
	/**
		The level of importance assigned to the resources associated with the finding. A score of 0 means that the underlying resources have no criticality, and a score of 100 is reserved for the most critical resources.
	**/
	@:optional
	var Criticality : Float;
	/**
		A finding's title.  In this release, Title is a required property.
	**/
	var Title : String;
	/**
		A finding's description.  In this release, Description is a required property.
	**/
	var Description : String;
	/**
		A data type that describes the remediation options for a finding.
	**/
	@:optional
	var Remediation : Remediation;
	/**
		A URL that links to a page about the current finding in the security-findings provider's solution.
	**/
	@:optional
	var SourceUrl : String;
	/**
		A data type where security-findings providers can include additional solution-specific details that aren't part of the defined AwsSecurityFinding format.
	**/
	@:optional
	var ProductFields : FieldMap;
	/**
		A list of name/value string pairs associated with the finding. These are custom, user-defined fields added to a finding.
	**/
	@:optional
	var UserDefinedFields : FieldMap;
	/**
		A list of malware related to a finding.
	**/
	@:optional
	var Malware : MalwareList;
	/**
		The details of network-related information about a finding.
	**/
	@:optional
	var Network : Network;
	/**
		Provides information about a network path that is relevant to a finding. Each entry under NetworkPath represents a component of that path.
	**/
	@:optional
	var NetworkPath : NetworkPathList;
	/**
		The details of process-related information about a finding.
	**/
	@:optional
	var Process : ProcessDetails;
	/**
		Threat intelligence details related to a finding.
	**/
	@:optional
	var ThreatIntelIndicators : ThreatIntelIndicatorList;
	/**
		A set of resource data types that describe the resources that the finding refers to.
	**/
	var Resources : ResourceList;
	/**
		This data type is exclusive to findings that are generated as the result of a check run against a specific rule in a supported security standard, such as CIS AWS Foundations. Contains security standard-related finding details.
	**/
	@:optional
	var Compliance : Compliance;
	/**
		Indicates the veracity of a finding.
	**/
	@:optional
	var VerificationState : String;
	/**
		The workflow state of a finding.
	**/
	@:optional
	var WorkflowState : String;
	/**
		Provides information about the status of the investigation into a finding.
	**/
	@:optional
	var Workflow : Workflow;
	/**
		The record state of a finding.
	**/
	@:optional
	var RecordState : String;
	/**
		A list of related findings.
	**/
	@:optional
	var RelatedFindings : RelatedFindingList;
	/**
		A user-defined note added to a finding.
	**/
	@:optional
	var Note : Note;
	/**
		Provides a list of vulnerabilities associated with the findings.
	**/
	@:optional
	var Vulnerabilities : VulnerabilityList;
};