package global.aws.apigateway;

typedef GatewayResponse = {
	/**
		The response type of the associated GatewayResponse. Valid values are ACCESS_DENIEDAPI_CONFIGURATION_ERRORAUTHORIZER_FAILURE AUTHORIZER_CONFIGURATION_ERRORBAD_REQUEST_PARAMETERSBAD_REQUEST_BODYDEFAULT_4XXDEFAULT_5XXEXPIRED_TOKENINVALID_SIGNATUREINTEGRATION_FAILUREINTEGRATION_TIMEOUTINVALID_API_KEYMISSING_AUTHENTICATION_TOKEN QUOTA_EXCEEDEDREQUEST_TOO_LARGERESOURCE_NOT_FOUNDTHROTTLEDUNAUTHORIZEDUNSUPPORTED_MEDIA_TYPE
	**/
	@:optional
	var responseType : String;
	/**
		The HTTP status code for this GatewayResponse.
	**/
	@:optional
	var statusCode : String;
	/**
		Response parameters (paths, query strings and headers) of the GatewayResponse as a string-to-string map of key-value pairs.
	**/
	@:optional
	var responseParameters : MapOfStringToString;
	/**
		Response templates of the GatewayResponse as a string-to-string map of key-value pairs.
	**/
	@:optional
	var responseTemplates : MapOfStringToString;
	/**
		A Boolean flag to indicate whether this GatewayResponse is the default gateway response (true) or not (false). A default gateway response is one generated by API Gateway without any customization by an API developer.
	**/
	@:optional
	var defaultResponse : Bool;
};