package global.aws.apigateway;

typedef Model = {
	/**
		The identifier for the model resource.
	**/
	@:optional
	var id : String;
	/**
		The name of the model. Must be an alphanumeric string.
	**/
	@:optional
	var name : String;
	/**
		The description of the model.
	**/
	@:optional
	var description : String;
	/**
		The schema for the model. For application/json models, this should be JSON schema draft 4 model. Do not include "\*" characters in the description of any properties because such "\*" characters may be interpreted as the closing marker for comments in some languages, such as Java or JavaScript, causing the installation of your API's SDK generated by API Gateway to fail.
	**/
	@:optional
	var schema : String;
	/**
		The content-type for the model.
	**/
	@:optional
	var contentType : String;
};