package global.aws.dynamodb;

typedef BinaryAttributeValue = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob_________________________________________________________________________________________________________________________________________________________________________________________________>;