package aws_sdk.securityhub;

typedef AwsSecurityFindingIdentifier = {
	/**
		The identifier of the finding that was specified by the finding provider.
	**/
	var Id : String;
	/**
		The ARN generated by Security Hub that uniquely identifies a product that generates findings. This can be the ARN for a third-party product that is integrated with Security Hub, or the ARN for a custom integration.
	**/
	var ProductArn : String;
};