package global.aws.lightsail;

typedef UpdateRelationalDatabaseRequest = {
	/**
		The name of your database to update.
	**/
	var relationalDatabaseName : String;
	/**
		The password for the master user of your database. The password can include any printable ASCII character except "/", """, or "@". Constraints: Must contain 8 to 41 characters.
	**/
	@:optional
	var masterUserPassword : String;
	/**
		When true, the master user password is changed to a new strong password generated by Lightsail. Use the get relational database master user password operation to get the new password.
	**/
	@:optional
	var rotateMasterUserPassword : Bool;
	/**
		The daily time range during which automated backups are created for your database if automated backups are enabled. Constraints:   Must be in the hh24:mi-hh24:mi format. Example: 16:00-16:30    Specified in Coordinated Universal Time (UTC).   Must not conflict with the preferred maintenance window.   Must be at least 30 minutes.
	**/
	@:optional
	var preferredBackupWindow : String;
	/**
		The weekly time range during which system maintenance can occur on your database. The default is a 30-minute window selected at random from an 8-hour block of time for each AWS Region, occurring on a random day of the week. Constraints:   Must be in the ddd:hh24:mi-ddd:hh24:mi format.   Valid days: Mon, Tue, Wed, Thu, Fri, Sat, Sun.   Must be at least 30 minutes.   Specified in Coordinated Universal Time (UTC).   Example: Tue:17:00-Tue:17:30
	**/
	@:optional
	var preferredMaintenanceWindow : String;
	/**
		When true, enables automated backup retention for your database. Updates are applied during the next maintenance window because this can result in an outage.
	**/
	@:optional
	var enableBackupRetention : Bool;
	/**
		When true, disables automated backup retention for your database. Disabling backup retention deletes all automated database backups. Before disabling this, you may want to create a snapshot of your database using the create relational database snapshot operation. Updates are applied during the next maintenance window because this can result in an outage.
	**/
	@:optional
	var disableBackupRetention : Bool;
	/**
		Specifies the accessibility options for your database. A value of true specifies a database that is available to resources outside of your Lightsail account. A value of false specifies a database that is available only to your Lightsail resources in the same region as your database.
	**/
	@:optional
	var publiclyAccessible : Bool;
	/**
		When true, applies changes immediately. When false, applies changes during the preferred maintenance window. Some changes may cause an outage. Default: false
	**/
	@:optional
	var applyImmediately : Bool;
	/**
		Indicates the certificate that needs to be associated with the database.
	**/
	@:optional
	var caCertificateIdentifier : String;
};