package aws_sdk;

@:jsRequire("aws-sdk", "TranscribeService") extern class TranscribeService extends Service {
	/**
		Constructs a service object. This object has one method for each API operation.
	**/
	function new(?options:aws_sdk.transcribeservice.ClientConfiguration);
	/**
		Creates a new custom vocabulary that you can use to change how Amazon Transcribe Medical transcribes your audio file.
		
		Creates a new custom vocabulary that you can use to change how Amazon Transcribe Medical transcribes your audio file.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.CreateMedicalVocabularyResponse) -> Void):Request<aws_sdk.transcribeservice.CreateMedicalVocabularyResponse, AWSError> { })
	function createMedicalVocabulary(params:aws_sdk.transcribeservice.CreateMedicalVocabularyRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.CreateMedicalVocabularyResponse) -> Void):Request<aws_sdk.transcribeservice.CreateMedicalVocabularyResponse, AWSError>;
	/**
		Creates a new custom vocabulary that you can use to change the way Amazon Transcribe handles transcription of an audio file.
		
		Creates a new custom vocabulary that you can use to change the way Amazon Transcribe handles transcription of an audio file.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.CreateVocabularyResponse) -> Void):Request<aws_sdk.transcribeservice.CreateVocabularyResponse, AWSError> { })
	function createVocabulary(params:aws_sdk.transcribeservice.CreateVocabularyRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.CreateVocabularyResponse) -> Void):Request<aws_sdk.transcribeservice.CreateVocabularyResponse, AWSError>;
	/**
		Creates a new vocabulary filter that you can use to filter words, such as profane words, from the output of a transcription job.
		
		Creates a new vocabulary filter that you can use to filter words, such as profane words, from the output of a transcription job.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.CreateVocabularyFilterResponse) -> Void):Request<aws_sdk.transcribeservice.CreateVocabularyFilterResponse, AWSError> { })
	function createVocabularyFilter(params:aws_sdk.transcribeservice.CreateVocabularyFilterRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.CreateVocabularyFilterResponse) -> Void):Request<aws_sdk.transcribeservice.CreateVocabularyFilterResponse, AWSError>;
	/**
		Deletes a transcription job generated by Amazon Transcribe Medical and any related information.
		
		Deletes a transcription job generated by Amazon Transcribe Medical and any related information.
	**/
	@:overload(function(?callback:(err:AWSError, data:{ }) -> Void):Request<{ }, AWSError> { })
	function deleteMedicalTranscriptionJob(params:aws_sdk.transcribeservice.DeleteMedicalTranscriptionJobRequest, ?callback:(err:AWSError, data:{ }) -> Void):Request<{ }, AWSError>;
	/**
		Deletes a vocabulary from Amazon Transcribe Medical.
		
		Deletes a vocabulary from Amazon Transcribe Medical.
	**/
	@:overload(function(?callback:(err:AWSError, data:{ }) -> Void):Request<{ }, AWSError> { })
	function deleteMedicalVocabulary(params:aws_sdk.transcribeservice.DeleteMedicalVocabularyRequest, ?callback:(err:AWSError, data:{ }) -> Void):Request<{ }, AWSError>;
	/**
		Deletes a previously submitted transcription job along with any other generated results such as the transcription, models, and so on.
		
		Deletes a previously submitted transcription job along with any other generated results such as the transcription, models, and so on.
	**/
	@:overload(function(?callback:(err:AWSError, data:{ }) -> Void):Request<{ }, AWSError> { })
	function deleteTranscriptionJob(params:aws_sdk.transcribeservice.DeleteTranscriptionJobRequest, ?callback:(err:AWSError, data:{ }) -> Void):Request<{ }, AWSError>;
	/**
		Deletes a vocabulary from Amazon Transcribe.
		
		Deletes a vocabulary from Amazon Transcribe.
	**/
	@:overload(function(?callback:(err:AWSError, data:{ }) -> Void):Request<{ }, AWSError> { })
	function deleteVocabulary(params:aws_sdk.transcribeservice.DeleteVocabularyRequest, ?callback:(err:AWSError, data:{ }) -> Void):Request<{ }, AWSError>;
	/**
		Removes a vocabulary filter.
		
		Removes a vocabulary filter.
	**/
	@:overload(function(?callback:(err:AWSError, data:{ }) -> Void):Request<{ }, AWSError> { })
	function deleteVocabularyFilter(params:aws_sdk.transcribeservice.DeleteVocabularyFilterRequest, ?callback:(err:AWSError, data:{ }) -> Void):Request<{ }, AWSError>;
	/**
		Returns information about a transcription job from Amazon Transcribe Medical. To see the status of the job, check the TranscriptionJobStatus field. If the status is COMPLETED, the job is finished. You find the results of the completed job in the TranscriptFileUri field.
		
		Returns information about a transcription job from Amazon Transcribe Medical. To see the status of the job, check the TranscriptionJobStatus field. If the status is COMPLETED, the job is finished. You find the results of the completed job in the TranscriptFileUri field.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.GetMedicalTranscriptionJobResponse) -> Void):Request<aws_sdk.transcribeservice.GetMedicalTranscriptionJobResponse, AWSError> { })
	function getMedicalTranscriptionJob(params:aws_sdk.transcribeservice.GetMedicalTranscriptionJobRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.GetMedicalTranscriptionJobResponse) -> Void):Request<aws_sdk.transcribeservice.GetMedicalTranscriptionJobResponse, AWSError>;
	/**
		Retrieve information about a medical vocabulary.
		
		Retrieve information about a medical vocabulary.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.GetMedicalVocabularyResponse) -> Void):Request<aws_sdk.transcribeservice.GetMedicalVocabularyResponse, AWSError> { })
	function getMedicalVocabulary(params:aws_sdk.transcribeservice.GetMedicalVocabularyRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.GetMedicalVocabularyResponse) -> Void):Request<aws_sdk.transcribeservice.GetMedicalVocabularyResponse, AWSError>;
	/**
		Returns information about a transcription job. To see the status of the job, check the TranscriptionJobStatus field. If the status is COMPLETED, the job is finished and you can find the results at the location specified in the TranscriptFileUri field. If you enable content redaction, the redacted transcript appears in RedactedTranscriptFileUri.
		
		Returns information about a transcription job. To see the status of the job, check the TranscriptionJobStatus field. If the status is COMPLETED, the job is finished and you can find the results at the location specified in the TranscriptFileUri field. If you enable content redaction, the redacted transcript appears in RedactedTranscriptFileUri.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.GetTranscriptionJobResponse) -> Void):Request<aws_sdk.transcribeservice.GetTranscriptionJobResponse, AWSError> { })
	function getTranscriptionJob(params:aws_sdk.transcribeservice.GetTranscriptionJobRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.GetTranscriptionJobResponse) -> Void):Request<aws_sdk.transcribeservice.GetTranscriptionJobResponse, AWSError>;
	/**
		Gets information about a vocabulary.
		
		Gets information about a vocabulary.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.GetVocabularyResponse) -> Void):Request<aws_sdk.transcribeservice.GetVocabularyResponse, AWSError> { })
	function getVocabulary(params:aws_sdk.transcribeservice.GetVocabularyRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.GetVocabularyResponse) -> Void):Request<aws_sdk.transcribeservice.GetVocabularyResponse, AWSError>;
	/**
		Returns information about a vocabulary filter.
		
		Returns information about a vocabulary filter.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.GetVocabularyFilterResponse) -> Void):Request<aws_sdk.transcribeservice.GetVocabularyFilterResponse, AWSError> { })
	function getVocabularyFilter(params:aws_sdk.transcribeservice.GetVocabularyFilterRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.GetVocabularyFilterResponse) -> Void):Request<aws_sdk.transcribeservice.GetVocabularyFilterResponse, AWSError>;
	/**
		Lists medical transcription jobs with a specified status or substring that matches their names.
		
		Lists medical transcription jobs with a specified status or substring that matches their names.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.ListMedicalTranscriptionJobsResponse) -> Void):Request<aws_sdk.transcribeservice.ListMedicalTranscriptionJobsResponse, AWSError> { })
	function listMedicalTranscriptionJobs(params:aws_sdk.transcribeservice.ListMedicalTranscriptionJobsRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.ListMedicalTranscriptionJobsResponse) -> Void):Request<aws_sdk.transcribeservice.ListMedicalTranscriptionJobsResponse, AWSError>;
	/**
		Returns a list of vocabularies that match the specified criteria. You get the entire list of vocabularies if you don't enter a value in any of the request parameters.
		
		Returns a list of vocabularies that match the specified criteria. You get the entire list of vocabularies if you don't enter a value in any of the request parameters.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.ListMedicalVocabulariesResponse) -> Void):Request<aws_sdk.transcribeservice.ListMedicalVocabulariesResponse, AWSError> { })
	function listMedicalVocabularies(params:aws_sdk.transcribeservice.ListMedicalVocabulariesRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.ListMedicalVocabulariesResponse) -> Void):Request<aws_sdk.transcribeservice.ListMedicalVocabulariesResponse, AWSError>;
	/**
		Lists transcription jobs with the specified status.
		
		Lists transcription jobs with the specified status.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.ListTranscriptionJobsResponse) -> Void):Request<aws_sdk.transcribeservice.ListTranscriptionJobsResponse, AWSError> { })
	function listTranscriptionJobs(params:aws_sdk.transcribeservice.ListTranscriptionJobsRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.ListTranscriptionJobsResponse) -> Void):Request<aws_sdk.transcribeservice.ListTranscriptionJobsResponse, AWSError>;
	/**
		Returns a list of vocabularies that match the specified criteria. If no criteria are specified, returns the entire list of vocabularies.
		
		Returns a list of vocabularies that match the specified criteria. If no criteria are specified, returns the entire list of vocabularies.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.ListVocabulariesResponse) -> Void):Request<aws_sdk.transcribeservice.ListVocabulariesResponse, AWSError> { })
	function listVocabularies(params:aws_sdk.transcribeservice.ListVocabulariesRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.ListVocabulariesResponse) -> Void):Request<aws_sdk.transcribeservice.ListVocabulariesResponse, AWSError>;
	/**
		Gets information about vocabulary filters.
		
		Gets information about vocabulary filters.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.ListVocabularyFiltersResponse) -> Void):Request<aws_sdk.transcribeservice.ListVocabularyFiltersResponse, AWSError> { })
	function listVocabularyFilters(params:aws_sdk.transcribeservice.ListVocabularyFiltersRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.ListVocabularyFiltersResponse) -> Void):Request<aws_sdk.transcribeservice.ListVocabularyFiltersResponse, AWSError>;
	/**
		Start a batch job to transcribe medical speech to text.
		
		Start a batch job to transcribe medical speech to text.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.StartMedicalTranscriptionJobResponse) -> Void):Request<aws_sdk.transcribeservice.StartMedicalTranscriptionJobResponse, AWSError> { })
	function startMedicalTranscriptionJob(params:aws_sdk.transcribeservice.StartMedicalTranscriptionJobRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.StartMedicalTranscriptionJobResponse) -> Void):Request<aws_sdk.transcribeservice.StartMedicalTranscriptionJobResponse, AWSError>;
	/**
		Starts an asynchronous job to transcribe speech to text.
		
		Starts an asynchronous job to transcribe speech to text.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.StartTranscriptionJobResponse) -> Void):Request<aws_sdk.transcribeservice.StartTranscriptionJobResponse, AWSError> { })
	function startTranscriptionJob(params:aws_sdk.transcribeservice.StartTranscriptionJobRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.StartTranscriptionJobResponse) -> Void):Request<aws_sdk.transcribeservice.StartTranscriptionJobResponse, AWSError>;
	/**
		Updates an existing vocabulary with new values in a different text file. The UpdateMedicalVocabulary operation overwrites all of the existing information with the values that you provide in the request.
		
		Updates an existing vocabulary with new values in a different text file. The UpdateMedicalVocabulary operation overwrites all of the existing information with the values that you provide in the request.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.UpdateMedicalVocabularyResponse) -> Void):Request<aws_sdk.transcribeservice.UpdateMedicalVocabularyResponse, AWSError> { })
	function updateMedicalVocabulary(params:aws_sdk.transcribeservice.UpdateMedicalVocabularyRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.UpdateMedicalVocabularyResponse) -> Void):Request<aws_sdk.transcribeservice.UpdateMedicalVocabularyResponse, AWSError>;
	/**
		Updates an existing vocabulary with new values. The UpdateVocabulary operation overwrites all of the existing information with the values that you provide in the request.
		
		Updates an existing vocabulary with new values. The UpdateVocabulary operation overwrites all of the existing information with the values that you provide in the request.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.UpdateVocabularyResponse) -> Void):Request<aws_sdk.transcribeservice.UpdateVocabularyResponse, AWSError> { })
	function updateVocabulary(params:aws_sdk.transcribeservice.UpdateVocabularyRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.UpdateVocabularyResponse) -> Void):Request<aws_sdk.transcribeservice.UpdateVocabularyResponse, AWSError>;
	/**
		Updates a vocabulary filter with a new list of filtered words.
		
		Updates a vocabulary filter with a new list of filtered words.
	**/
	@:overload(function(?callback:(err:AWSError, data:aws_sdk.transcribeservice.UpdateVocabularyFilterResponse) -> Void):Request<aws_sdk.transcribeservice.UpdateVocabularyFilterResponse, AWSError> { })
	function updateVocabularyFilter(params:aws_sdk.transcribeservice.UpdateVocabularyFilterRequest, ?callback:(err:AWSError, data:aws_sdk.transcribeservice.UpdateVocabularyFilterResponse) -> Void):Request<aws_sdk.transcribeservice.UpdateVocabularyFilterResponse, AWSError>;
	static var prototype : TranscribeService;
}