package aws_sdk.kms;

typedef CiphertextType = ts.AnyOf4<String, global.Buffer, js.lib.Uint8Array, aws_sdk.Blob_________________________________________________________________________________________________________________________________________________________________________>;