package aws_sdk.athena;

typedef ListTableMetadataOutput = {
	/**
		A list of table metadata.
	**/
	@:optional
	var TableMetadataList : TableMetadataList;
	/**
		A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call.
	**/
	@:optional
	var NextToken : String;
};