package aws_sdk.athena;

typedef ListWorkGroupsOutput = {
	/**
		The list of workgroups, including their names, descriptions, creation times, and states.
	**/
	@:optional
	var WorkGroups : WorkGroupsList;
	/**
		A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call.
	**/
	@:optional
	var NextToken : String;
};