package aws_sdk.apigateway;

typedef PutMethodRequest = {
	/**
		[Required] The string identifier of the associated RestApi.
	**/
	var restApiId : String;
	/**
		[Required] The Resource identifier for the new Method resource.
	**/
	var resourceId : String;
	/**
		[Required] Specifies the method request's HTTP method type.
	**/
	var httpMethod : String;
	/**
		[Required] The method's authorization type. Valid values are NONE for open access, AWS_IAM for using AWS IAM permissions, CUSTOM for using a custom authorizer, or COGNITO_USER_POOLS for using a Cognito user pool.
	**/
	var authorizationType : String;
	/**
		Specifies the identifier of an Authorizer to use on this Method, if the type is CUSTOM or COGNITO_USER_POOLS. The authorizer identifier is generated by API Gateway when you created the authorizer.
	**/
	@:optional
	var authorizerId : String;
	/**
		Specifies whether the method required a valid ApiKey.
	**/
	@:optional
	var apiKeyRequired : Bool;
	/**
		A human-friendly operation identifier for the method. For example, you can assign the operationName of ListPets for the GET /pets method in the PetStore example.
	**/
	@:optional
	var operationName : String;
	/**
		A key-value map defining required or optional method request parameters that can be accepted by API Gateway. A key defines a method request parameter name matching the pattern of method.request.{location}.{name}, where location is querystring, path, or header and name is a valid and unique parameter name. The value associated with the key is a Boolean flag indicating whether the parameter is required (true) or optional (false). The method request parameter names defined here are available in Integration to be mapped to integration request parameters or body-mapping templates.
	**/
	@:optional
	var requestParameters : MapOfStringToBoolean;
	/**
		Specifies the Model resources used for the request's content type. Request models are represented as a key/value map, with a content type as the key and a Model name as the value.
	**/
	@:optional
	var requestModels : MapOfStringToString;
	/**
		The identifier of a RequestValidator for validating the method request.
	**/
	@:optional
	var requestValidatorId : String;
	/**
		A list of authorization scopes configured on the method. The scopes are used with a COGNITO_USER_POOLS authorizer to authorize the method invocation. The authorization works by matching the method scopes against the scopes parsed from the access token in the incoming request. The method invocation is authorized if any method scopes matches a claimed scope in the access token. Otherwise, the invocation is not authorized. When the method scope is configured, the client must provide an access token instead of an identity token for authorization purposes.
	**/
	@:optional
	var authorizationScopes : ListOfString;
};