package aws_sdk.glacier;

typedef Stream = ts.AnyOf5<String, global.Buffer, node.stream.Readable, js.lib.Uint8Array, aws_sdk.Blob__________________________________________________________________________________________________________________________________________________________________________________>;